services:
  chat-db:
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chat-data:/var/lib/postgresql/data

  chat-redis:
    image: redis:7.4.0
    container_name: chat-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - chat-session:/data

volumes:
  chat-data:
  chat-session:
