services:
  chat-db:
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chat-data:/var/lib/postgresql/data

  chat-redis:
    image: redis:7.4.0
    container_name: chat-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - chat-session:/data

  rabbitmq:
    image: rabbitmq:4-alpine
    container_name: chat-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  chat-data:
  chat-session:
