{
 "title": "Chatapp Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Requests over 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(job) (count_over_time({job=\"api-server\"} | json | res_statusCode != `` [24h]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(res_statusCode) (count_over_time({job=\"api-server\"} | json | res_statusCode != `` [24h]))",
     "legendFormat": "Http Status: {{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Recent Requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api-server\"} | json | res_statusCode != \"\" | line_format `{{.req_method}} {{.req_url}} with response status code {{.res_statusCode}}`"
    }
   ]
  },
  {
   "title": "Errors over 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"api-server\", level=\"error\"} [24h]))"
    }
   ]
  },
  {
   "title": "Warning over 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"api-server\", level=\"warning\"} [24h]))"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api-server\"} | json"
    }
   ]
  }
 ]
}